# 本次分析的名称，唯一标识符。名称可以含有字母，数字和下划线，只能以字母开头，区分大小写
analysis: myAnalysis
# 数据是idat格式还是β矩阵格式，如果是β矩阵格式，则该值为true，否则为false
import: false
# β矩阵文件，如果是idat文件，该值为false
matrixfile: false
## 如果import为true，则还需要提供对应的P值文件，否则该值设置为false
detPfile: false
# 芯片类型。如果是450k芯片，则为450k；如果是850k芯片，则为EPIC。目前仅支持这两种芯片
chiptype: 450k
# 表型文件路径。该文件是实验配置文件，记录了分组等信息,该文件需要和idat文件或者β矩阵文件放在同一个文件夹下面
pdfile: lung_test_set.csv
# 目录路径。idat或者β文件矩阵所在的文件夹路径
directory: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChAMPdata/extdata
# 数据导入方法。如果是idat文件，导入方法可选ChAMP或者minfi，否则设为false，表示从β矩阵导入
loadmethod: ChAMP
# 数据过滤指标参数
## 探针阈值。P值高于该阈值的探针会被认为错误造成的
detPcut: 0.01
## 探针在样本中NA的比例，高于该比例的探针将会被剔除
probecutoff: 0.2
## 样本中失败探针阈值。高于该阈值的样本将被剔除
samplecutoff: 0.1
## 人群信息。
population: TRUE
## 是否过滤性染色体
filterXY: TRUE
# β值标准化方法。可选方法有：BMIQ、PBC、SWAN、FunctionalNormalize
normMethod: BMIQ
## 核数
cores: 2
# 差显探针校正后阈值
diffexprProbeP: 0.05
# 差显区域检测方法。可选方法：Bumphunter、DMRcate、Probelasso
dmrMethod: ProbeLasso
# DMR区域最小探针数
minProbe: 7
# 差显区域的P值
diffexprRegionP: 0.05
# DMR计算核数
dmrcores: 2
# DMR的最大长度
maxGap: 300
# 探针是否被包含在DMR中的最小P值
adjPprobe: 0.05
# 差显甲基化块的最大阈值
bpScan: 250000
# 比较组。两个比较组用“_vs_”隔开
compGroup: 
    - A_vs_B
    - B_vs_C
    - C_vs_D
# 基因集富集方法。可选方法：gometh，fisher，ebayes
gseaMethod: gometh
gseaPvalue: 0.05
# CNV变异检测的比较基准组.比如bpfile中定义的normal组
controlGroup: normal
# CNV检测阈值
freqThreshold: 0.05
# 样本类型。如果为血液样本，则为blood，可以用来分析细胞类型杂合度；否则为other，不做杂合度分析
sampleType: blood
